apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deploy
  labels:
    app: ui-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui-container
        image: roshenreji/kubernetes-ui
        ports:
        - containerPort: 4200
  selector:
    matchLabels:
      app: ui-app