apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress
spec:
  selector:
    matchLabels:
      app: postgress
  template:
    metadata:
      labels:
        app: postgress
    spec:
      containers:
      - name: postgress
        image: roshenreji/kubernetes-postgress:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgress-service
spec:
  selector:
    app: postgress
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5432
      nodePort: 30000