apiVersion: apps/v1
kind: Deployment`
metadata:
  name: postgress
spec:
  selector:
    matchLabels:
      app: postgress
  template:
    metadata:
      labels:
        app: postgress
    spec:
      containers:
      - name: postgress
        image: roshenreji/kubernetes-postgress:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgreiss
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
     
